### ISSUE TITLE
请问可以将H264/AMR的视频转码压缩成H264/AAC的吗？

### ISSUE THREAD

**Issue by wxh12138** [yellowcath/VideoProcessor#3]
请问可以将H264/AMR的视频转码压缩成H264/AAC的吗？

**Comment by yellowcath** [comment]
没有直接提供这个函数，但是你可以用我的函数自行实现，
1、用AudioUtil.decodeToPCM解码为PCM
2、再参考AudioUtil 760行把PCM拼成WAV
3、AudioUtil.encodeWAVToAAC()

**Comment by wxh12138** [comment]
谢谢，思路我清楚了，再请教一下，这样会不会大大降低编码的效率，因为我就是嫌FFmpeg转码效率太低了，然后看到您的实现方法，看看能不能在高压缩的情况下还能提高转码的效率。

**Comment by yellowcath** [comment]
不会的，转码都是要先转成pcm再转到指定格式的。你可以试一试，肯定比ffmpeg快
不过我说的这个步骤只针对纯音频，如果你是想视频带音频一起转的话，可以走process函数，
，增加一个输出音频格式，然后在AudioProcessThread里面如果检查到输入和输出音频格式不一致，就走79行 AudioUtil.writeAudioTrackDecode，在里面把输出格式改成你指定的就行

**Comment by wxh12138** [comment]
按照您说的，我在进入AudioProcessThread  65 行 doProcessAudio()，之后就报错了。

```
09-21 09:58:41.880 14211-15487/com.hw.videoprocessor D/MPEG4Writer: Writer thread stopped
09-21 09:58:41.882 14211-15487/com.hw.videoprocessor E/MediaMuxer: java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:245)
        at android.media.MediaMuxer.release(MediaMuxer.java:485)
        at com.hw.videoprocessor.VideoProcessor.processVideo(VideoProcessor.java:293)
        at com.hw.videoprocessor.VideoProcessor$Processor.process(VideoProcessor.java:1085)
        at com.hw.videoprocessor.demo.MainActivity$11.run(MainActivity.java:409)
        at java.lang.Thread.run(Thread.java:761)
09-21 09:58:41.882 14211-15487/com.hw.videoprocessor W/System.err: java.lang.IllegalStateException
        at android.media.MediaExtractor.nativeSetDataSource(Native Method)
        at android.media.MediaExtractor.setDataSource(MediaExtractor.java:186)
09-21 09:58:41.883 14211-15487/com.hw.videoprocessor W/System.err:     at com.hw.videoprocessor.AudioProcessThread.doProcessAudio(AudioProcessThread.java:66)
        at com.hw.videoprocessor.AudioProcessThread.run(AudioProcessThread.java:56)
```

**Comment by yellowcath** [comment]
我刚才研究了一下，发现有点问题
你指的H264/AMR是 f4v格式的文件么？如果是的话，Android是不支持这个格式的，你需要自行找一个库把它的音视频分开，然后可以用我第一个回复里的方法把音频单独转换成aac，再自己把它合成回去

**Comment by yellowcath** [comment]
合成回去可以用VideoProcessor.mixAudioTrack()

**Comment by wxh12138** [comment]
我的视频源是H264/AMR的.mp4文件，然后是把它转码成H264/AAC的.mp4文件。

**Comment by yellowcath** [comment]
这个没问题，能传一个视频到网盘上么？我测试一下

**Comment by wxh12138** [comment]
嗯呢，厉害，再请教一个问题，这个好像只能转码本地视频，不能拉取 rtsp / rtmp / http ...... 的流视频存储吧，还是也可以有方法实现的。

**Comment by yellowcath** [comment]
是的，数据都是来自MediaExtractor，这个只支持本地。想要拉网上的就要自己实现一个数据源。
