### ISSUE TITLE
IllegalArgumentException in mixAudio (passing url string)

### ISSUE THREAD

**Issue by vikas-patel** [yellowcath/VideoProcessor#4]
Hey,

I am getting the following error on execution of code. It seems videoprocessor only supports local audio file path and doesn't support external audio url.

```
String audioPath = mMusicUri.toString();
VideoProcessor.mixAudioTrack(mRecordShareView.getActivity(), file.getAbsolutePath(), audioPath, mixFile.getAbsolutePath(), null, null, 0,
                                    100, 1f, 1f);
```

```
java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:71)
        at com.hw.videoprocessor.VideoProcessor.mixAudioTrack(VideoProcessor.java:674)
        at com.demo.photomovie.RecordSharePresenter$3.onRecordFinish(RecordSharePresenter.java:228)
```

**Comment by yellowcath** [comment]
yes,It is recommended that downloading it first
